reference: hs38DH
samples:
    - HG003
    - HG004
sample_ploidy: 2
sample_depth: 35
library: NovaSeq
mapper: bwa
depths:
    - 10
    - 20
    - 30
    - 40
    - 50
    - 60
    - 70
callers:
    - Octopus
    - GATK4
    - FreeBayes
score_fields:
    Octopus: RFGQ
    GATK4: GQ
    FreeBayes: GQ
