reference: hs38DH
samples:
    - HG002
sample_ploidy: 2
sample_depth: 35
library: NovaSeq
mapper: bwa
depths:
    - 10
    - 20
    - 30
callers:
    - Octopus
    - GATK4
    - FreeBayes
caller_options:
    Octopus: ""
    GATK4: ""
    FreeBayes: ""
score_fields:
    Octopus: GQ
    GATK4: GQ
    FreeBayes: GQ
stratifications:
    - genome
    - alldifficult
    - alllowmapandsegdup
    - notinalldifficult
    - notinalllowmapandsegdup
    - AllTandemRepeatsandHomopolymers
    - notinAllTandemRepeatsandHomopolymers
