reference: GRCh38
samples:
    - HG002
sample_ploidy: 2
sample_depth: 35
library: PacBioHiFi
mapper: pbmm2
depths:
    - 35
callers:
    - Octopus
    - GATK4
    - FreeBayes
caller_options:
    Octopus: "--max-genotypes 20000 --disable-early-phase-detection"
    GATK4: ""
    FreeBayes: "-="
score_fields:
    Octopus: RFGQ
    GATK4: GQ
    FreeBayes: GQ
