reference: hs38DH
samples:
    - HG003
    - HG004
sample_ploidy: 2
sample_depth: 35
library: PacBioHifi
mapper: pbmm2
depths:
    - 10
    - 20
    - 30
    - 40
    - 50
    - 60
    - 70
callers:
    - Octopus
    - GATK4
    - FreeBayes
caller_options:
    Octopus: "--max-genotypes 20000 --disable-early-phase-detection"
    GATK4: ""
    FreeBayes: "-="
score_fields:
    Octopus: RFGQ
    GATK4: GQ
    FreeBayes: GQ
